# Generated by Django 2.1.4 on 2019-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'Other')], max_length=1)),
                ('last_location_longitude', models.CharField(help_text="0 to 180 W/E e.g 172º 23' 23'' E", max_length=20)),
                ('last_location_latitude', models.CharField(help_text="0 to 90 N/S e.g 80º 21' 25'' N", max_length=20)),
                ('infected', models.BooleanField(default=False)),
                ('water', models.IntegerField()),
                ('food', models.IntegerField()),
                ('medication', models.IntegerField()),
                ('ammunition', models.IntegerField()),
                ('reports', models.IntegerField(default=0)),
            ],
        ),
    ]
