# Generated by Django 2.1.4 on 2018-12-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='last_location_latitude',
            field=models.CharField(help_text="80º21'25''N", max_length=11),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='last_location_longitude',
            field=models.CharField(help_text="172º23'23''E", max_length=12),
        ),
    ]
