# Generated by Django 2.1.4 on 2018-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0002_auto_20181224_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='last_location_latitude',
            field=models.CharField(help_text="0 to 90 N/S e.g 80º 21' 25'' N", max_length=20),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='last_location_longitude',
            field=models.CharField(help_text="0 to 180 W/E e.g 172º 23' 23'' E", max_length=20),
        ),
    ]
