# Generated by Django 2.1.4 on 2018-12-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0003_auto_20181225_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
