# Generated by Django 2.1.4 on 2018-12-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0004_survivor_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infected_survivors', models.DecimalField(decimal_places=2, max_digits=6)),
                ('non_infected_survivors', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_water', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_food', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_medication', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amount_ammunition', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
