# Generated by Django 2.1.4 on 2018-12-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0005_reports'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
